<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDEKVIrA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDEKVIrA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDEKVIrA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDEKVIrA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDEKVIrA\App_KernelProdContainer([
    'container.build_hash' => 'DEKVIrA',
    'container.build_id' => '38dd3b02',
    'container.build_time' => 1623505532,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDEKVIrA');
