<?php

namespace ContainerDEKVIrA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6lhXv7GService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6lhXv7G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6lhXv7G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repo' => ['privates', 'App\\Repository\\AdRepository', 'getAdRepositoryService', true],
        ], [
            'paginator' => '?',
            'repo' => 'App\\Repository\\AdRepository',
        ]);
    }
}
